version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "bengbenz"
